// Generated by tools/build_episode.py - do not edit.
// The menu theme plus this episode's world tracks.
XGM jj1_music_menu     "music/menu.vgm"
XGM jj1_music_world0  "music/diamondus.vgm"
XGM jj1_music_world1  "music/tubelectric.vgm"
XGM jj1_music_world2  "music/medivo.vgm"
