#ifndef JJ1_RUNTIME_H
#define JJ1_RUNTIME_H

/* Converted level data (generated by tools/build_sgdk_jj1_level_data.py)
 * and the platform-neutral runtime queries built on it. */

#ifdef JAZZ_HOST
#include <stdint.h>
#else
#include <types.h>
#endif

#include "jazz_game.h"

/* Which 4x4 mask row inside a 32x32 cell the bridge deck occupies (0-7). The
 * span is drawn near the top of its cell, so only the first row is standable. */
#define JJ1_BRIDGE_DECK_CELL 1

/* The shareware ships eight levels across three worlds. */
extern const u8 jj1_level0_blocks[256 * 64];
extern const u8 jj1_level0_events[256 * 64];
extern const u8 jj1_level0_masks[(240 + 16) * 8];
extern const u16 jj1_level0_start_x, jj1_level0_start_y;
extern const u8 jj1_level1_blocks[256 * 64];
extern const u8 jj1_level1_events[256 * 64];
extern const u8 jj1_level1_masks[(240 + 16) * 8];
extern const u16 jj1_level1_start_x, jj1_level1_start_y;
extern const u8 jj1_level2_blocks[256 * 64];
extern const u8 jj1_level2_events[256 * 64];
extern const u8 jj1_level2_masks[(240 + 16) * 8];
extern const u16 jj1_level2_start_x, jj1_level2_start_y;
extern const u8 jj1_level3_blocks[256 * 64];
extern const u8 jj1_level3_events[256 * 64];
extern const u8 jj1_level3_masks[(240 + 16) * 8];
extern const u16 jj1_level3_start_x, jj1_level3_start_y;
extern const u8 jj1_level4_blocks[256 * 64];
extern const u8 jj1_level4_events[256 * 64];
extern const u8 jj1_level4_masks[(240 + 16) * 8];
extern const u16 jj1_level4_start_x, jj1_level4_start_y;
extern const u8 jj1_level5_blocks[256 * 64];
extern const u8 jj1_level5_events[256 * 64];
extern const u8 jj1_level5_masks[(240 + 16) * 8];
extern const u16 jj1_level5_start_x, jj1_level5_start_y;
extern const u8 jj1_level6_blocks[256 * 64];
extern const u8 jj1_level6_events[256 * 64];
extern const u8 jj1_level6_masks[(240 + 16) * 8];
extern const u16 jj1_level6_start_x, jj1_level6_start_y;
extern const u8 jj1_level7_blocks[256 * 64];
extern const u8 jj1_level7_events[256 * 64];
extern const u8 jj1_level7_masks[(240 + 16) * 8];
extern const u16 jj1_level7_start_x, jj1_level7_start_y;

u8 jj1_runtime_event(u8 stage, s16 blockX, s16 blockY);
u8 jj1_runtime_point_solid(u8 stage, s16 x, s16 y);
u8 jj1_runtime_down_point_solid(u8 stage, s16 x, s16 y);
u8 jj1_runtime_rect_solid(u8 stage, s16 x, s16 y, s16 w, s16 h);
u8 jj1_runtime_solid(u8 stage, s16 tx, s16 ty);
u16 jj1_runtime_spring_height(u8 stage, s16 x, s16 y, s16 w, s16 h, s16 *springTopY);
/* Sucker-tube push (8.8 px/frame) following the tube's own orientation.
 * Fills the pushX and pushY outputs, returning non-zero when inside a tube. */
/* Sucker tube probe: 0 = none, 1 = horizontal (fills *pushX), 2 = vertical
 * launch (fills *pushX drift and *targetY, the pixel Y to lift the player to). */
u8 jj1_runtime_tube_push(u8 stage, s16 x, s16 y, s16 w, s16 h, s16 *pushX, s16 *targetY);
u8 jj1_runtime_touches_end(u8 stage, s16 x, s16 y, s16 w, s16 h);
void jj1_runtime_place_player(JazzGame *state, u8 stage);

#endif
