/* Generated by tools/build_episode.py - do not edit. */
#ifndef JJ1_EPISODE_H
#define JJ1_EPISODE_H
#define JJ1_EPISODE_NUMBER 1
#define JJ1_EPISODE_STAGES 7
#define JJ1_EPISODE_TITLE "EPISODE 1"
#define JJ1_EPISODE_WORLDS "DIAMONDUS TUBELECTRIC MEDIVO"
#endif
