#!/usr/bin/env python3
"""Generate every per-level include and stage table for one episode.

The build used to enumerate a fixed eight stages in three separate places
(the art table in gfx.c, the event-set table in jj1_eventset.c, and
JAZZ_STAGE_COUNT).  Those are now produced here from the episode's own level
chain, so pointing the build at a different episode is a matter of running this
with a different --episode.

Tiles and sprites are resolved separately per level, because a guardian stage
borrows another world's tiles while shipping its own sprite bank.  Assuming one
implied the other is what made a boss draw as unrelated enemies.

Usage:
    python3 tools/build_episode.py --input DIR --episode 1

World tile banks are generated on demand by build_world_tiles.py, so an episode
in any world set can be built.  A bank already present is left alone, which
keeps the checked-in shareware banks authoritative for episode 1.
"""
import argparse
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from discover_episodes import episodes, describe  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
TOOLS = ROOT / "tools"


def run(script: str, *args: str) -> None:
    cmd = [sys.executable, str(TOOLS / script), *args]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode:
        sys.stderr.write(result.stdout + result.stderr)
        raise SystemExit(f"{script} failed for: {' '.join(args)}")


def generate(data_dir: Path, episode: int, out_src: Path, out_inc: Path) -> int:
    runs = episodes(data_dir)
    if not 1 <= episode <= len(runs):
        raise SystemExit(f"episode {episode} not present; found {len(runs)}")
    stages = describe(data_dir, runs[episode - 1])

    worlds = sorted({s["blocks"] for s in stages})
    # Each world's terrain bank, produced once and shared by its levels.  The
    # shareware banks were checked in; anything else has to be generated here.
    for world in worlds:
        target = out_src / f"jj1_world{world}_tiles.inc"
        if not target.exists():
            run("build_world_tiles.py", "--input", str(data_dir),
                "--world", world, "--output", str(target))
    # `--shared` emits a single jazz_world_tiles symbol, so it can only be used
    # by one level per build.  An episode spanning several worlds therefore
    # still needs per-world tile banks (jj1_world<NNN>_tiles.inc), which no tool
    # here generates yet - see the note in the module docstring.
    shared_done = False
    for index, stage in enumerate(stages):
        name = f"jj1_level{index}"
        run("build_sgdk_jj1_level_data.py",
            "--input", str(data_dir), "--level", stage["level"], "--name", name,
            "--output", str(out_src / f"{name}_data.inc"),
            "--eventset", str(out_src / f"{name}_eventset.inc"))
        visual_args = ["--input", str(data_dir), "--level", stage["level"],
                       "--world", stage["blocks"], "--sprite-world", stage["sprites"],
                       "--name", name, "--output", str(out_src / f"{name}_visuals.inc")]
        if not shared_done:
            visual_args.append("--shared")
            shared_done = True
        run("build_sgdk_jj1_visuals.py", *visual_args)

    # Includes: world tile banks, then each level's data and visuals.
    lines = ["/* Generated by tools/build_episode.py - do not edit. */"]
    for world in worlds:
        lines.append(f'#include "jj1_world{world}_tiles.inc"')
    for index in range(len(stages)):
        lines.append(f'#include "jj1_level{index}_data.inc"')
    for index in range(len(stages)):
        lines.append(f'#include "jj1_level{index}_visuals.inc"')
    (out_src / "jj1_episode_includes.inc").write_text("\n".join(lines) + "\n")

    # Level data alone, for builds that have no graphics types (the host tests).
    lines = ["/* Generated by tools/build_episode.py - do not edit. */"]
    for index in range(len(stages)):
        lines.append(f'#include "jj1_level{index}_data.inc"')
    (out_src / "jj1_episode_data.inc").write_text("\n".join(lines) + "\n")

    # The art table, one STAGE entry per level, each naming its own tile world.
    lines = ["/* Generated by tools/build_episode.py - do not edit. */"]
    for index, stage in enumerate(stages):
        lines.append(f'    STAGE({index}, {stage["blocks"]}),')
    (out_src / "jj1_episode_stages.inc").write_text("\n".join(lines) + "\n")

    # Event sets: the includes and the per-stage lookup table.
    lines = ["/* Generated by tools/build_episode.py - do not edit. */"]
    for index in range(len(stages)):
        lines.append(f'#include "jj1_level{index}_eventset.inc"')
    (out_src / "jj1_episode_eventsets.inc").write_text("\n".join(lines) + "\n")

    lines = ["/* Generated by tools/build_episode.py - do not edit. */"]
    for index in range(len(stages)):
        lines.append(f"    jj1_level{index}_eventset,")
    (out_src / "jj1_episode_eventset_table.inc").write_text("\n".join(lines) + "\n")

    # Runtime level data: one switch case per stage past the first, which is
    # the default.
    lines = ["/* Generated by tools/build_episode.py - do not edit. */"]
    for index in range(1, len(stages)):
        lines += [f"    case {index}:",
                  f"        d.blocks = jj1_level{index}_blocks; "
                  f"d.masks = jj1_level{index}_masks;",
                  f"        d.events = jj1_level{index}_events;",
                  f"        d.startX = jj1_level{index}_start_x; "
                  f"d.startY = jj1_level{index}_start_y; break;"]
    (out_src / "jj1_episode_leveldata.inc").write_text("\n".join(lines) + "\n")

    # Soundtrack: the menu theme plus one track per world this episode visits.
    # Worlds map to planets in file order and the converted set covers the
    # first fifteen; a world past that reuses a track so the build still runs.
    planets = ["diamondus", "tubelectric", "medivo", "letni", "technoir",
               "orbitus", "nippius", "fanolint", "scraparap", "megairbase",
               "turtemple", "pezrock", "dreempipes", "deckstar", "battleships"]
    music_dir = ROOT / "res" / "music"
    world_tracks = []
    for world in worlds:
        index = int(world)
        track = planets[index] if index < len(planets) else planets[index % len(planets)]
        if not (music_dir / (track + ".vgm")).exists():
            track = "diamondus"
        world_tracks.append(track)

    lines = ["// Generated by tools/build_episode.py - do not edit.",
             "// The menu theme plus this episode's world tracks.",
             'XGM jj1_music_menu     "music/menu.vgm"']
    for slot, track in enumerate(world_tracks):
        lines.append('XGM jj1_music_world%d  "music/%s.vgm"' % (slot, track))
    (ROOT / "res" / "jj1_music.res").write_text("\n".join(lines) + "\n")

    # Which track each stage plays.
    lines = ["/* Generated by tools/build_episode.py - do not edit. */",
             "static const u8 *const jj1_stage_music[JJ1_EPISODE_STAGES] = {"]
    for stage in stages:
        lines.append("    jj1_music_world%d," % worlds.index(stage["blocks"]))
    lines.append("};")
    (out_src / "jj1_episode_music.inc").write_text("\n".join(lines) + "\n")

    # Stage count, so the rest of the port sizes its tables to this episode.
    (out_inc / "jj1_episode.h").write_text(
        "/* Generated by tools/build_episode.py - do not edit. */\n"
        "#ifndef JJ1_EPISODE_H\n"
        "#define JJ1_EPISODE_H\n"
        f"#define JJ1_EPISODE_NUMBER {episode}\n"
        f"#define JJ1_EPISODE_STAGES {len(stages)}\n"
        '#define JJ1_EPISODE_TITLE "EPISODE %d"\n' % episode +
        '#define JJ1_EPISODE_WORLDS "%s"\n' % " ".join(t.upper() for t in world_tracks) +
        "#endif\n")
    return len(stages)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--input", type=Path, required=True)
    ap.add_argument("--episode", type=int, default=1)
    ap.add_argument("--src", type=Path, default=ROOT / "src")
    ap.add_argument("--inc", type=Path, default=ROOT / "inc")
    args = ap.parse_args()
    count = generate(args.input, args.episode, args.src, args.inc)
    print(f"episode {args.episode}: generated {count} stages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
